;
; ExternalPinInterruptV1.asm
;
; Created: 3/6/2019 8:49:04 PM
; Author : clayt
;

; This example is looking for a logical LOW at PinD2 which is also INT0.
; When the interrupt is triggered, the output at PinB5 is toggled. It resets
; and waits for another interrupt to repeat. 

; PortD2 will be set High and is looking to be set logical Low using a switch attached to ground.

.ORG 0; LOCATION FOR RESET
JMP MAIN

.ORG 0x02 ; Location for external interrupt stack location
JMP EXO_ISR

MAIN:
	LDI R20, HIGH(RAMEND)
	OUT SPH, R20 ; LOAD HIGH BYTE OF STACKPOINTER TO INITIALIZE
	LDI R20, LOW(RAMEND) 
	OUT SPL, R20

	LDI R20, 0x2 ; CONFIGURE INTERRUPT TO OCCUR INT0 FOR FALLING EDGE TRIGGER
	STS EICRA, R20 ; LOAD CONFIGURE INTO REGISTER
	SBI DDRB, 5 ; SET PORTB PIN 5 AS OUTPUT
	SBI PORTD, 2 ; SET PORTD PIN 2 AS INPUT, SET PULL UP RESISTOR
	LDI R20, 1<< INT0 ; ENABLE EXTERNAL INTERRUPT INT0
	OUT EIMSK, R20 ; LOAD ENABLE INTO REGISTER
	SEI ; GLOBAL INTERRUPT ENABLE COMMAND

HERE: JMP HERE ; LOOP HERE UNTIL THE INTERRUPT IS OCCURS

; INTERRUPT SUBROUTINE
EXO_ISR:
	IN R21, PORTB ; INPUT CURRENT VALUE OF PORTB INTO R21
	LDI R22, (1<<5) ; 00100000, USED FOR TOGGLING PB5
	EOR R21, R22 ; XOR R21 AND R22 AND STORE IN R21
	OUT PORTB, R21 ; OUTPUT NEW VALUE OF R21 INTO PORTB
	RETI ; RETURN FROM INTERRUPT